[package]
name = "vulkano-and-ash_vulkano"
version = "0.1.0"
authors = ["Brandon Pollack <brandonpollack23@gmail.com>"]
edition = "2018"

[[bin]]
name = "base_code_vulkano"
path = "src/00_base_code.rs"

[dependencies]
vulkano = "0.17.0"
winit = "0.21.0"
